### ISSUE TITLE
The link to Resnet finetuned model is broken

### ISSUE THREAD

**Issue by JustinWeru12** [RAHUL-KAD/Reverse-Image-Search-Engine#3]
The link provided to ResNet finetuned model is broken, and  the file can't be accessed. Could you please update the file link or provide an alternative download link

**Comment by RAHUL-KAD** [comment]
Here is a dataset and google colab link to train a model. 

https://drive.google.com/drive/folders/1JhQcphga-_MLVtNSknt6Jqp1bLCq-jp7?usp=sharing

Hope this helps.
